# Generated by Django 5.0.4 on 2024-07-19 07:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0002_fun_categories_listechats_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='related_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
